### ISSUE TITLE
badge: <language> for <@tio sam>

### ISSUE THREAD

**Issue by sIeepcall** [revoltchat/translations#183] opened 2023-05-09 01:43 UTC
### What language(s) did you translate?

Portuguese, Chinese , French

### What is your Revolt ID?

01GZVMCSEWJHJE4MJ0AKR112SX

### Link to Weblate profile

https://weblate.insrt.uk/user/tiosam/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-05-09 01:53
Closing as a duplicate of #181.

**Closed by Rexogamer** 2023-05-09 01:53 UTC
