### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by DantumFlandrox** [revoltchat/translations#201] opened 2023-05-23 19:50 UTC
### What language(s) did you translate?

Ukrain, Russian

### What is your Revolt ID?

01H14VRHCR9KBBWCWHW6MN2WE3

### Validations

- [x] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-05-25 05:58
Duplicate of #200.

**Closed by Rexogamer** 2023-05-25 05:58 UTC
