### ISSUE TITLE
badge: Turkish for ramazaneris

### ISSUE THREAD

**Issue by ramazaneris** [revoltchat/translations#104] opened 2023-01-26 17:20 UTC
### What language(s) did you translate?

Turkish

### What is your Revolt ID?

01FCXFBQPYCBZWX40NSBYXYAWW

### Link to Weblate profile

https://weblate.insrt.uk/user/Jeosty/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-01-26 17:34
cc @kerizalperwastaken

**Comment by ramazaneris** [comment] 2023-06-03 21:39
I'm still waiting

**Comment by Rexogamer** [comment] 2023-06-06 20:25
Duplicate of #159.

**Closed by Rexogamer** 2023-06-06 20:25 UTC
Labels: status: pending
