### ISSUE TITLE
maintain: <language>

### ISSUE THREAD

**Issue by sIeepcall** [revoltchat/translations#182] opened 2023-05-09 01:29 UTC
### What language do you want to maintain?

Portuguese, Chinese , French

### Link to Weblate profile

https://weblate.insrt.uk/user/tiosam/

### Revolt ID

01GZVMCSEWJHJE4MJ0AKR112SX

**Comment by Rexogamer** [comment] 2023-05-09 01:53
Closing as a duplicate of #181.

**Closed by Rexogamer** 2023-05-09 01:53 UTC
