### ISSUE TITLE
badge: Pig Latin for TesticalCutter

### ISSUE THREAD

**Issue by Test1calCutter** [revoltchat/translations#136] opened 2023-03-16 20:07 UTC
### What language(s) did you translate?

Pig Latin

### What is your Revolt ID?

01GVJYBQXPCNX8VE5Y4R9JFX6G

### Link to Weblate profile

https://weblate.insrt.uk/user/TesticalCutter/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-03-16 20:11
Duplicate of #133

**Closed by Rexogamer** 2023-03-16 20:11 UTC
