### ISSUE TITLE
badge: french for Âchlys

### ISSUE THREAD

**Issue by Achlys12** [revoltchat/translations#241] opened 2023-06-16 11:39 UTC
### What language(s) did you translate?

French

### What is your Revolt ID?

01H1P7PFR9XJSEHX03JA5BQDA9

### Link to Weblate profile

https://weblate.insrt.uk/user/Achlys/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-06-17 03:42
cc @Hades785

**Comment by Hades785** [comment] 2023-06-17 09:10
I think your translations are fine, not the greatest but not bad. Most of the ones on the android app did a good clean-up pass after the initial rush.
A few suggestions I accepted and then edited to fix small issues (missing capital letter, double space, not too bad but needed fixing anyway), but I don't think that really discredits you, they're just small mistakes.

Nothing outrageous stood out so I feel that it would be fine for you to get the translator badge for your work, but I'd also like to know what @Kasahe might think about it.

**Comment by Kasahe** [comment] 2023-06-17 09:15
Hello, I agree with @Hades785 and I have also accepted one of his suggestions and we have also spoken privately about translations on revolt. @Rexogamer 👍

**Comment by Rexogamer** [comment] 2023-07-04 03:43
Duplicate of #246.

**Closed** 2023-07-04 03:43 UTC
Labels: status: approved
