### ISSUE TITLE
badge: <language> for <your name>

### ISSUE THREAD

**Issue by PWGod** [revoltchat/translations#112] opened 2023-02-22 19:21 UTC
### What language(s) did you translate?

Russian, English 

### What is your Revolt ID?

<@01GSX5DHKJYVG1ZW8EK9KKB8CZ> 

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment] 2023-02-23 12:28
Duplicate of #114.

**Closed by Rexogamer** 2023-02-23 12:28 UTC
